project:
  type: book
  
lang: es
always_allow_html: yes
cover-image: img/leaves-2874583_1280.jpg
bibliography: referencias.bib
csl: apa.csl
css: estilo.css

lightbox: true

citation: 
  type: book
  
book:
  navbar: 
    title: "**Aviso** - [requisitos posgrado](posgrado/requerimientos-posgrado.html)"

  title: "Ciencia reproducible para la política pública"
  author:
     - name: Miguel Equihua Zamora
       affiliation: Ambiente y Sustetabilidad, Inecol, México
     - name: Octavio Pérez-Maqueo
     - name: Elio Lagunes Díaz
  date: "5/7/2025"
  downloads: [pdf]
  favicon: img/box-2071537_640.png
  cover-image: img/leaves-2874583_1280.jpg
  
profile: 
  default: completo
  group: [completo,posgrado]


format:
  html:
    theme: minty
    
  pdf:
    prefer-html: true
    

