---
title: "Posgrado"
editor: visual
---

# Requisitos para el posgrado

## Datos Generales

Nombre:

Horas: (minimo 30):

Créditos (1 por 10 horas):

Tipo :OP

Cupo mínimo:

Se requieren 4 para abrir el curso por parte del Posgrado. El profesor puede establecer el número mínimo para su curso

Cupo máximo

Precio al público sugerido por el Coordinador:

**Costo estimado por el sistema de acuerdo al MOP**
$ 1,125.00

Gastos:

Comentarios para el estudiante:

Notas para el CAP:

Sede:

Comentarios para el personal administrativo:

Fecha inicio

Fecha fin

Periodo

Hora Inicio

Hora Fin

Descripción del horario

Fecha Inicio de Inscripción Externos

Fecha Límite Inscripción Externos

## Contenido

### Presentación

### Objetivo

### Objetivos específicos

### Metodología

### Prerequisitos

### Habilidades y destrezas requeridas

### Habilidades y destrezas por adquirir

### Criterios de calificación

### Contenido temático

### Bibliografía

## Coordinadores

## Profesores invitados

## Materiales

## Gastos invitados

## Gastos prácticas de campo

## Mobiliario y equipo

## Otros gastos





